import type { EditorThemeClasses } from 'lexical';
import './index.less';

export const DefaultTheme: EditorThemeClasses = {
  autocomplete: 'default-theme-autocomplete',
  characterLimit: 'default-theme-character-limit',
  code: 'default-theme-code',
  codeHighlight: {
    atrule: 'default-theme-token-attr',
    attr: 'default-theme-token-attr',
    boolean: 'default-theme-token-property',
    builtin: 'default-theme-token-selector',
    cdata: 'default-theme-token-comment',
    char: 'default-theme-token-selector',
    class: 'default-theme-token-function',
    'class-name': 'default-theme-token-function',
    comment: 'default-theme-token-comment',
    constant: 'default-theme-token-property',
    deleted: 'default-theme-token-property',
    doctype: 'default-theme-token-comment',
    entity: 'default-theme-token-operator',
    function: 'default-theme-token-function',
    important: 'default-theme-token-variable',
    inserted: 'default-theme-token-selector',
    keyword: 'default-theme-token-attr',
    namespace: 'default-theme-token-variable',
    number: 'default-theme-token-property',
    operator: 'default-theme-token-operator',
    prolog: 'default-theme-token-comment',
    property: 'default-theme-token-property',
    punctuation: 'default-theme-token-punctuation',
    regex: 'default-theme-token-variable',
    selector: 'default-theme-token-selector',
    string: 'default-theme-token-selector',
    symbol: 'default-theme-token-property',
    tag: 'default-theme-token-property',
    url: 'default-theme-token-operator',
    variable: 'default-theme-token-variable',
  },
  embedBlock: {
    base: 'default-theme-token-embed-block',
    focus: 'default-theme-token-embed-block-focus',
  },
  hashtag: 'default-theme-token-embed-hashtag',
  heading: {
    h1: 'default-theme-h1',
    h2: 'default-theme-h2',
    h3: 'default-theme-h3',
  },
  hr: 'default-theme-hr',
  image: 'editor-image',
  indent: 'default-theme-indent',
  inlineImage: 'inline-editor-image',
  layoutContainer: 'default-theme-layout-container',
  layoutItem: 'default-theme-layout-item',
  link: 'default-theme-link',
  list: {
    listitem: 'default-theme-list-item',
    listitemChecked: 'default-theme-list-item-checked',
    listitemUnchecked: 'default-theme-list-item-unchecked',
    nested: {
      listitem: 'default-theme-nested-list-item',
    },
    olDepth: [
      'default-theme-ol1',
      'default-theme-ol2',
      'default-theme-ol3',
      'default-theme-ol4',
      'default-theme-ol5',
    ],
    ul: 'default-theme-ul',
  },
  ltr: 'default-theme-ltr',
  mark: 'default-theme-mark',
  markOverlap: 'default-theme-mark-overlap',
  paragraph: 'default-theme-paragraph',
  quote: 'default-theme-quote',
  rtl: 'default-theme-rtl',
  tableBox: 'default-theme-tablebox',
  table: 'default-theme-table',
  tableCell: 'default-theme-table-cell',
  tableCellActionButton: 'default-theme-table-cell-action-button',
  tableCellActionButtonContainer:
    'default-theme-tableC-cell-action-button-container',
  tableCellEditing: 'default-theme-table-cell-editing',
  tableCellHeader: 'default-theme-table-cell-header',
  tableCellPrimarySelected: 'default-theme-table-cell-primary-selected',
  tableCellResizer: 'default-theme-table-cell-resizer',
  tableCellSelected: 'default-theme-table-cell-selected',
  tableCellSortedIndicator: 'default-theme-table-cell-sorted-indicator',
  tableResizeRuler: 'default-theme-table-cell-resize-ruler',
  tableSelected: 'default-theme-table-selected',
  tableSelection: 'default-theme-table-selection',
  text: {
    bold: 'default-theme-text-bold',
    code: 'default-theme-text-code',
    italic: 'default-theme-text-italic',
    strikethrough: 'default-theme-text-strikethrough',
    subscript: 'default-theme-text-subscript',
    superscript: 'default-theme-text-superscript',
    underline: 'default-theme-text-underline',
    underlineStrikethrough: 'default-theme-text-underline-strikethrough',
  },
};
